from django.core.exceptions import ValidationError


def adult_kid_validation(value):
    pass
